# Generated by Django 3.2 on 2021-05-31 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CookingApp', '0003_remove_post_dateposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
