# Generated by Django 3.2 on 2021-05-31 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210531_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='datePosted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
